# -*- coding: utf-8 -*-
"""customer_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11a6Y0zwD_k9edxwO04ZCjK9Wj1BVfJHL
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Customer data
data = "/content/Mall_Customers.csv"
# Load data into a pandas DataFrame
df = pd.read_csv(data) # Use pd.read_csv() to read the data from the CSV file

# Select features for clustering
X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

# Apply KMeans clustering
kmeans = KMeans(n_clusters=5, random_state=42)
kmeans.fit(X)

# Add the cluster labels to the DataFrame
df['Cluster'] = kmeans.labels_

# Plotting the clusters
plt.figure(figsize=(10, 8))
plt.scatter(df['Annual Income (k$)'], df['Spending Score (1-100)'], c=df['Cluster'], cmap='viridis', marker='o', s=100, alpha=0.6, edgecolors='w')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Customer Segments')
plt.colorbar(label='Cluster')
plt.grid(True)
plt.show()

# Print the first few rows of the dataframe to verify cluster assignments
print(df.head())